adding denormalizeCamel Unit Test
striven-erp/striven-editor pull request #142
Opened 2020-10-01 15:06 UTC by SuchismitaDhal

Test for #140
Added assertions for the function

2020-10-01 15:29 UTC, unitehenry requested changes

2020-10-02 13:01 UTC, unitehenry commented
@SuchismitaDhal This looks good. I'll resolve the conflicts, but thank you for your contribution!

2020-10-02 13:17 UTC, SuchismitaDhal commented
I guess my code editor autoformatted the code :sweat_smile: 
I will be careful next time. Thank you for helping me out!

2020-10-02 13:55 UTC, unitehenry commented
> I guess my code editor autoformatted the code 😅
> I will be careful next time. Thank you for helping me out!

This repo desperately needs to implement a linter like https://eslint.org/

2020-10-02 15:03 UTC, closed without merging