Strikethrough Test
striven-erp/striven-editor pull request #145
Opened 2020-10-02 17:36 UTC by rach-m

Hi - I am having some sort of an error here and would appreciate a second set of eyes. By what I have seen in the other tests the code here should run but it seems that the strikethrough style is being applied too late or not at all. I tried using a timeout function but that led to even more errors. Please let me know if you have any solutions

2020-10-05 12:40 UTC, unitehenry requested changes

2020-10-05 12:40 UTC, unitehenry commented on demo/src/test.js
> +        se.getRange().selectNode(se.body.querySelector("p"));
From ```selectNode``` to ```onfocus```, you can wrap this in a ```setTimeout```. When you call ```assert```, that should be in another ```setTimeout```.

```js
// establish content

setTimeout(() => {
    
    // apply strikethrough 

    setTimeout(() => {
         // make assertions
        done();
    }, 200)
}, 0)
```

2020-10-05 14:51 UTC, rach-m commented
So I made that change and I still get `Error: Script error. (:0)` with no other information. Any ideas?

2020-10-07 19:26 UTC, unitehenry commented
@rach-m The change looks good but I'm not sure what is causing that error.

I'm going to pull this in and try it for myself, but if you figure it out before then let me know. I'll merge this in regardless.

Thanks for your help 😄

2020-10-09 18:24 UTC, closed without merging